### ISSUE TITLE
trackingco.de serving content related to... house building?!

### ISSUE THREAD

**Issue by hartwork** [fiatjaf/trackingco.de#3]
Hi!

This is what I am being presented at https://trackingco.de/ right now:

![trackingcode_Screenshot_20210216_040016](https://user-images.githubusercontent.com/1577132/108013257-9a438700-700b-11eb-859b-fcb491b5dc4c.png)

Is the server mis-configured or did your sell your domain to a third party?

Best, Sebastian

**Comment by fiatjaf** [comment]
Haha, that's funny, but no, sorry. I didn't sell the domain, it expired naturally many years ago after I failed a dozen times to get attention and users for the service.

Coincidentally, at the same time no one was caring at all to the selling point of trackingco.de (being very simple, non-invasive and cheap), many other similar services began to appear and make huge success.

**Comment by hartwork** [comment]
@fiatjaf thanks for your reply! What do you think about mass-replacing links to https://trackingco.de/ by links to https://trackingcode.invalid/ (see https://en.wikipedia.org/wiki/Top-level_domain#Reserved_domains for `.invalid`) or so, so that I would be the last to follow those links? I could help with a pull request if you can take over the project page link and like the idea. Just let me know. Best!

**Comment by fiatjaf** [comment]
There are no links to trackingco.de anywhere.

**Comment by hartwork** [comment]
> There are no links to trackingco.de anywhere.

You just replaced the project link. Thanks!

With regard to the content, yes, there are:
```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/fiatjaf/trackingco.de
# cd trackingco.de/
# git --no-pager grep -E https?://trackingco.de | wc -l
4
```
